apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld
  namespace: helloworld
spec:
  rules:
  - host: helloworld.your-link
    http:
      paths:
      - path: /hello-world
        pathType: Prefix
        backend:
          service:
            name: helloworld
            port:
              number: 3000
  ingressClassName: nginx