#!/bin/bash

set -e

BUCKET=${BUCKET:-lab-statefiles-101}
export AWS_REGION="ap-southeast-2"
export AWS_DEFAULT_REGION="ap-southeast-2"
export AWS_PROFILE=${AWS_PROFILE:-aws-cert1}
export NAME=kops.awslab.telephony.city
export KOPS_STATE_STORE=s3://${BUCKET}
export ZONES=${ZONES:-ap-southeast-2a}


aws sts get-caller-identity
if ! [ "$?" -eq 0 ]; then
    echo "Check aws cli credentials"
    exit 255
fi

if ! aws s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
    aws s3api create-bucket \
        --bucket ${BUCKET} \
        --create-bucket-configuration LocationConstraint=ap-southeast-2
    if [ "$?" -ne "0" ];then
    echo "Error creating bucket"
    exit 1
    fi

    aws s3api put-bucket-versioning \
        --bucket ${BUCKET}  \
        --versioning-configuration Status=Enabled

    if [ "$?" -ne "0" ];then
    echo "Error configuring bucket"
    exit 1
    fi

    aws s3api put-bucket-encryption \
    --bucket ${BUCKET}  \
    --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
    if [ "$?" -ne "0" ];then
    echo "Error configuring bucket encryption"
    exit 1
    fi
fi

if ! kops get cluster 2>/dev/null; then
    kops create cluster \
        --zones=${ZONES} \
        ${NAME}      

    kops update cluster --name ${NAME} --yes --admin

    kops validate cluster --name ${NAME} --wait 10m
fi