#!/bin/bash

set -e

BUCKET=${BUCKET:-lab-statefiles-101}
export AWS_REGION="ap-southeast-2"
export AWS_DEFAULT_REGION="ap-southeast-2"
export AWS_PROFILE=${AWS_PROFILE:-aws-cert1}
export NAME=kops.awslab.telephony.city
export KOPS_STATE_STORE=s3://${BUCKET}
export ZONES=${ZONES:-ap-southeast-2a}

kops delete cluster --name=${NAME} --yes

